---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: conjur-cluster
  namespace: dap

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conjur-authenticator
rules:
- apiGroups: [""]
  resources: ["pods", "serviceaccounts"]
  verbs: ["get", "list"]
- apiGroups: ["extensions"]
  resources: [ "deployments", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: [ "deployments", "statefulsets", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: conjur-authenticator
subjects:
- kind: ServiceAccount
  name: conjur-cluster
  namespace: dap
roleRef:
  kind: ClusterRole
  name: conjur-authenticator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dap-access-node
  namespace: dap
  labels:
    app: cyberark
spec:
  replicas: 1
  selector:
    matchLabels:
      role: access
  template:
    metadata:
      labels:
        role: access
    spec:
      serviceAccountName: conjur-cluster
      volumes:
      - name: seedfile
        emptyDir:
          medium: Memory
      - name: conjur-token
        emptyDir:
          medium: Memory
      initContainers:
      - name: authenticator
        image: captainfluffytoes/seed-fetcher:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: CONJUR_SEED_FILE_URL
            value: https://source.dap.svc.cluster.local/configuration/cyberark/seed/follower
          - name: SEEDFILE_DIR
            value: /tmp/seedfile
          - name: FOLLOWER_HOSTNAME
            value: access
          - name: AUTHENTICATOR_ID
            value: k8s-follower
          - name: CONJUR_ACCOUNT
            value: cyberark
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: k8s-app-ssl
                key: ssl-certificate
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_AUTHN_LOGIN
            value: "host/conjur/authn-k8s/k8s-follower/apps/dap/service_account/conjur-cluster"
        volumeMounts:
          - name: seedfile
            mountPath: /tmp/seedfile
          - name: conjur-token
            mountPath: /run/conjur
      containers:
      - name: node
        imagePullPolicy: IfNotPresent
        image: captainfluffytoes/dap:10.10
        command: ["/tmp/seedfile/start-follower.sh"]
        env:
          - name: CONJUR_AUTHENTICATORS
            value: "authn-k8s/okd-follower,authn-k8s/k8s-follower"
          - name: SEEDFILE_DIR
            value: /tmp/seedfile
        ports:
          - containerPort: 443
            protocol: TCP
          - containerPort: 5432
            protocol: TCP
          - containerPort: 1999
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
          - name: seedfile
            mountPath: /tmp/seedfile
            readOnly: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "500m"
            
---
apiVersion: v1
kind: Service
metadata:
  name: access
  namespace: dap
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
  selector:
    role: access
  type: ClusterIP

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: follower-scaler
  namespace: dap
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dap-access-node
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50